CREATE TABLE TEAM(TID INT IDENTITY(1,1),TEAM_NAME VARCHAR(20) NOT NULL,CREATED_ON DATETIME NOT NULL)

ALTER TABLE TEAM ADD CONSTRAINT PK_PRIMARY PRIMARY KEY( TID)

ALTER TABLE TEAM ADD CONSTRAINT CNST_DEFAULT DEFAULT GETDATE() FOR CREATED_ON
ALTER TABLE TEAM ADD POINTS INT DEFAULT 0 NOT NULL
ALTER TABLE TEAM DROP COLUMN POINTS 
ALTER TABLE TEAM DROP CONSTRAINT DF__TEAM__POINTS__3B75D760


CREATE TABLE TEAM_MATCH(TMID INT IDENTITY(1,1),TEAM1 INT NOT NULL,TEAM2 INT NOT NULL,PLAYED_ON DATETIME NOT NULL)
ALTER TABLE TEAM_MATCH ADD CONSTRAINT PK_TEAM_MATCH PRIMARY KEY( TMID)
ALTER TABLE TEAM_MATCH ADD CONSTRAINT DEFAULT_PLAYED_ON DEFAULT GETDATE() FOR PLAYED_ON
